-- Create inventory items table
CREATE TABLE public.inventory_items (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  categoria TEXT NOT NULL,
  material TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 0,
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create movements table
CREATE TABLE public.inventory_movements (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  item_id UUID NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
  material TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'saida')),
  quantidade INTEGER NOT NULL,
  horario TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  observacoes TEXT
);

-- Enable Row Level Security (public access for now)
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
CREATE POLICY "Anyone can view inventory items" 
ON public.inventory_items 
FOR SELECT 
USING (true);

CREATE POLICY "Anyone can create inventory items" 
ON public.inventory_items 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Anyone can update inventory items" 
ON public.inventory_items 
FOR UPDATE 
USING (true);

CREATE POLICY "Anyone can delete inventory items" 
ON public.inventory_items 
FOR DELETE 
USING (true);

CREATE POLICY "Anyone can view inventory movements" 
ON public.inventory_movements 
FOR SELECT 
USING (true);

CREATE POLICY "Anyone can create inventory movements" 
ON public.inventory_movements 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Anyone can update inventory movements" 
ON public.inventory_movements 
FOR UPDATE 
USING (true);

CREATE POLICY "Anyone can delete inventory movements" 
ON public.inventory_movements 
FOR DELETE 
USING (true);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_inventory_items_updated_at
BEFORE UPDATE ON public.inventory_items
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert inventory data
INSERT INTO public.inventory_items (categoria, material, quantidade, observacoes) VALUES
('Q30', 'TRELIÇA 10CM', 21, NULL),
('Q30', 'TRELIÇA 20CM', 94, NULL),
('Q30', 'TRELIÇA 30CM', 82, NULL),
('Q30', 'TRELIÇA 40CM', 67, NULL),
('Q30', 'TRELIÇA 50CM', 71, NULL),
('Q30', 'TRELIÇA 60CM', 16, NULL),
('Q30', 'TRELIÇA 1M', 113, NULL),
('Q30', 'TRELIÇA 1.35M', 5, NULL),
('Q30', 'TRELIÇA 1.5M', 133, NULL),
('Q30', 'TRELIÇA 1.60M', 17, NULL),
('Q30', 'TRELIÇA 2M', 220, NULL),
('Q30', 'TRELIÇA 2.5M', 13, NULL),
('Q30', 'TRELIÇA 2.90M', 11, NULL),
('Q30', 'TRELIÇA 3M', 248, NULL),
('Q30', 'TRELIÇA 4M', 224, NULL),
('Q30', 'TRELIÇA 5M', 300, NULL),
('Q30', 'TRELIÇA 6M', 18, NULL),
('Q30', 'CUBO', 412, NULL),
('Q30', 'SLEEVE', 88, NULL),
('Q30', 'BASE', 93, NULL),
('Q30', 'ÂNGULO', 137, NULL),
('Q30', 'ÂNGULO 15º', 48, NULL),
('Q30', 'CUMIEIRA', 80, NULL),
('Q30', 'TRIÂNGULO', 20, NULL),
('Q30', 'PAU DE CARGA', 93, NULL),
('Q30', 'ARCO', 48, NULL),
('Q30', 'CUMIEIRA NATAL', 28, NULL),
('Q30', 'GRAU 15', 56, NULL),
('Q15', 'TRELIÇA 50CM', 8, NULL),
('Q15', 'TRELIÇA 1M', 8, NULL),
('Q15', 'TRELIÇA 1.5M', 6, NULL),
('Q15', 'TRELIÇA 2M', 7, NULL),
('Q15', 'TRELIÇA 3M', 10, NULL),
('Q15', 'CUBO', 18, NULL),
('Q15', 'BASE', 10, NULL),
('Q25', 'TRELIÇA 2M', 15, NULL),
('Q25', 'TRELIÇA 1.5M', 6, NULL),
('Q25', 'TRELIÇA 1M', 9, NULL),
('Q25', 'CUBO', 5, NULL),
('Q25', 'BASE PQ.', 4, NULL),
('Q25', 'BASE G', 2, NULL),
('Q50', 'TRELIÇA 1M', 17, NULL),
('Q50', 'TRELIÇA 2M', 14, NULL),
('Q50', 'TRELIÇA 3M', 22, NULL),
('Q50', 'TRELIÇA 4M', 6, NULL),
('Q50', 'CUBO', 12, NULL),
('Q50', 'CUBO C/ FACE Q30', 6, NULL),
('Q50', 'CUMIEIRA', 4, NULL),
('Q50', 'CUMIEIRA C/ FACE Q30', 3, NULL),
('PISO', 'TABLADO', 965, NULL),
('PISO', 'PRATICÁVEL', 141, NULL),
('PISO', 'FEELING', 1506, NULL),
('PISO', 'EASYFLOOR', 1657, NULL),
('PISO', 'EASYFLOOR ROLO 1.5X10', 41, NULL),
('PISO QUADRO', 'QUADRO', 106, NULL),
('PISO QUADRO', 'MÃO FRANCESA G.', 41, NULL),
('PISO QUADRO', 'MÃO FRANCESA M.', 151, NULL),
('PISO QUADRO', 'MÃO FRANCESA P.', 330, NULL),
('PISO QUADRO', 'REGULAD. ALTURA', 210, NULL),
('PISO QUADRO', 'ALONGADOR', 180, NULL),
('PISO QUADRO', 'TRAVA ALONGADOR', 305, NULL),
('PISO QUADRO', 'ESCADA', 1, NULL),
('PISO QUADRO', 'GUARDA CORPO ESC.', 2, NULL),
('GAURDA CORPO', 'FERRO 2M', 40, NULL),
('GAURDA CORPO', 'FERRO 1M', 5, NULL),
('GAURDA CORPO', 'ALUMINIO 2M', 22, NULL),
('GAURDA CORPO', 'ALUMINIO 1M', 1, NULL),
('PISO FEELING', 'POSTE 2 ORELHAS', 61, NULL),
('PISO FEELING', 'POSTE 3 ORELHAS', 34, '146 NOVO'),
('PISO FEELING', 'TRAVESSA 2.5', 860, '160 NOVO'),
('PISO FEELING', 'TRAVESSA 1.25', 530, '100 NOVO'),
('PISO FEELING', 'GAURDACORPO 2.5', 63, '64 NOVO'),
('PISO FEELING', 'GAURDACORPO 1.25', 0, '30 NOVO'),
('PISO FEELING', 'MÃO FRANCESA', 177, '200 NOVO'),
('PISO FEELING', 'TRAVA MÃO FRANC.', 328, '400 NOVO'),
('PISO FEELING', 'PE DE 20 CM', 90, '50 NOVO'),
('PISO FEELING', 'PE DE 40 CM', 82, '50 NOVO'),
('PISO FEELING', 'PE DE 70 CM', 78, '50 NOVO'),
('PISO FEELING', 'PE DE 1.35', 295, '60 NOVO'),
('PISO FEELING', 'TRAVESSA RAMPA G.', 10, NULL),
('PISO FEELING', 'TRAVESSA RAMPA P.', 3, NULL),
('PISO FEELING', 'PONTA RAMPA', 2, NULL),
('PISO FEELING', 'TRAVA PÉ', 440, '30 NOVO'),
('PISO FEELING', 'ESCADA 2M FEELING', 2, NULL),
('TENDAS NOVAS', 'TENDA 3X3 C/ BALCÃO', 50, NULL),
('TENDAS NOVAS', 'TENDA 4X4', 20, NULL),
('TENDAS NOVAS', 'TENDA 5X5', 20, NULL),
('TENDAS NOVAS', 'TENDA 6X6', 20, NULL),
('TENDAS NOVAS', 'TENDA 8X8', 20, NULL),
('TENDAS NOVAS', 'TENDA 10X10', 20, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 3X3', 5, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 4X4', 21, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 5X5', 14, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 6X6', 19, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 8X8', 10, NULL),
('TENDA ANTIGA C/ LONA NOVA', 'TENDA 10X10', 10, NULL),
('FECHAMENTO', 'FECHAMENTO 3X2.5', 32, NULL),
('FECHAMENTO', 'FECHAMENTO 4X2.5', 32, NULL),
('FECHAMENTO', 'FECHAMENTO 5X3', 32, NULL),
('FECHAMENTO', 'FECHAMENTO 6X3', 20, NULL),
('FECHAMENTO', 'FECHAMENTO 8X3', 20, NULL),
('FECHAMENTO', 'FECHAMENTO 10X3', 40, NULL),
('CALHA', 'CALHA 3M', 20, NULL),
('CALHA', 'CALHA 4M', 40, NULL),
('CALHA', 'CALHA 5M', 40, NULL),
('CALHA', 'CALHA 6M', 20, NULL),
('CALHA', 'CALHA 8M', 30, NULL),
('CALHA', 'CALHA 10M', 40, NULL),
('LONA GALPÃO', 'LONA GALPÃO 10X5', 23, '7 RETAS E 2 TRIÂNGULOS NOVOS'),
('LONA GALPÃO', 'LONA GALPÃO 15X5', 8, NULL),
('LONA GALPÃO', 'LONA GALPÃO CRISTAL 10X5', 20, NULL),
('LONA PALCO', '6X6', 4, NULL),
('LONA PALCO', '8X8', 5, NULL),
('LONA PALCO', '9X6', 3, NULL),
('LONA PALCO', '10X8', 8, NULL),
('LONA PALCO', '12X10', 3, NULL),
('LONA PALCO', '14X10', 2, NULL),
('LONA PALCO', '18X14', 2, NULL),
('LONA PALCO', '5X5 (1 ÁGUA)', 23, 'SENDO 4 PONTAS'),
('OUTROS', 'TALHA', 84, NULL),
('OUTROS', 'CINTA CARGA', 94, NULL),
('OUTROS', 'BARRICADA', 90, NULL),
('OUTROS', 'UNIFILA', 18, NULL),
('OUTROS', 'FITA 9M/15M/17M', 380, '24/15MT E 30/17MT - 150/9MT'),
('OUTROS', 'CATRACA', 430, '54 P/15 E 17MT - 150/P 9MT'),
('OUTROS', 'MESA PLAST.', 99, NULL),
('OUTROS', 'CADEIRA PLAST.', 497, NULL),
('OUTROS', 'PESO 100 KG', 20, NULL),
('OUTROS', 'CABO AÇO 16.5M', 22, NULL),
('OUTROS', 'CABO AÇO 12 M', 64, '48 NOVO'),
('OUTROS', 'CABO AÇO 3M', 30, NULL),
('OUTROS', 'CABO AÇO 9.35M', 36, 'NOVO'),
('OUTROS', 'CABO AÇO 4M', 48, 'NOVO'),
('OUTROS', 'GALÃO 60LT', 90, NULL),
('OUTROS', 'BALCÃO FRENTE', 49, NULL),
('OUTROS', 'BALCÃO LATERAL', 100, NULL),
('OUTROS', 'TRAVESSA BALCÃO', 100, NULL),
('OUTROS', 'SAIA BALCÃO 9M', 30, NULL),
('OUTROS', 'OLHAL', 200, NULL),
('OUTROS', 'RESERVATÓRIO', 76, NULL),
('OUTROS', 'PARAFUSO Q30', 5300, NULL),
('OUTROS', 'RAMPA FERRO 10CM', 3, NULL),
('OUTROS', 'RAMPA MADEIRA 10CM', 5, NULL),
('OUTROS', 'RAMPA MADEIRA 20CM', 2, NULL),
('OUTROS', 'RAMPA MADEIRA 35CM', 2, NULL),
('OUTROS', 'RAMPA MADEIRA 40CM', 2, NULL),
('OUTROS', 'RAMPA MADEIRA 50CM', 2, NULL),
('OUTROS', 'RAMPA MADEIRA 60CM', 2, NULL),
('OUTROS', 'ESCADA 2M FEELING', 2, NULL),
('OUTROS', 'ESCADA MADEIRA 50 CM', 5, NULL),
('OUTROS', 'ESCADA MADEIRA 55 CM', 2, NULL),
('OUTROS', 'ESCADA MADEIRA 60 CM', 3, NULL),
('OUTROS', 'ESCADA MADEIRA 70 CM', 2, NULL),
('OUTROS', 'ESCADA MADEIRA 1M', 3, NULL),
('OUTROS', 'ESCADA MADEIRA 1.5M', 2, NULL),
('OUTROS', 'ESCADA APOIAR 60 CM', 1, NULL),
('OUTROS', 'ESCADA APOIAR 1M', 3, NULL),
('OUTROS', 'ESCADA APOIAR 1.5M', 3, NULL),
('OUTROS', 'ESCADA FERRO 50 CM', 1, NULL),
('OUTROS', 'ESCADA FERRO 80 CM', 3, NULL),
('OUTROS', 'ESCADA 20 A 1.80 CM', 1, NULL),
('OUTROS', 'DEGRAU MADEIRA 20 CM', 3, NULL),
('OUTROS', 'TAPADEIRA', 97, NULL),
('ALMOXARIFADO', 'ENCERADEIRA', 3, NULL),
('ALMOXARIFADO', 'CAPACETE', 40, NULL),
('ALMOXARIFADO', 'CINTO + TALABARTE', 20, NULL),
('ALMOXARIFADO', 'PARAFUSADEIRA DEWALT', 14, NULL),
('ALMOXARIFADO', 'BATERIA', 15, NULL),
('ALMOXARIFADO', 'CARREGADOR', 9, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 8"', 1, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 11"', 2, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 13"', 8, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 14"', 8, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 17"', 8, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 19"', 1, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 22"', 7, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 24"', 11, NULL),
('ALMOXARIFADO', 'SOQUETE SEXTAVADO 27"', 11, NULL),
('ALMOXARIFADO', 'MARTELETE(DEWALT) + BROCA 1"', 1, NULL),
('ALMOXARIFADO', 'ROCAMA STANLEY', 7, NULL),
('ALMOXARIFADO', 'ALICATE UNIVERSAL', 2, NULL),
('ALMOXARIFADO', 'ALICATE DE CORTE', 2, NULL),
('ALMOXARIFADO', 'TRENA 3MT', 1, NULL),
('ALMOXARIFADO', 'TRENA C/RODA', 1, NULL),
('ALMOXARIFADO', 'NÍVEL LASER', 1, NULL),
('ALMOXARIFADO', 'MARTELO', 2, NULL),
('ALMOXARIFADO', 'CHAVE PHILIPS', 2, NULL),
('ALMOXARIFADO', 'CHAVE FENDA', 2, NULL),
('ALMOXARIFADO', 'TORQUESA', 4, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 6"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 7"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 10"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 11"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 12"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 13"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 14"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 15"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 17"', 4, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 18"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 19"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 22"', 2, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 24"', 1, NULL),
('ALMOXARIFADO', 'CHAVE FREZADA 27"', 2, NULL),
('ALMOXARIFADO', 'CHAVE L 11"', 3, NULL),
('ALMOXARIFADO', 'MARRETA BORRACHA', 3, NULL),
('ALMOXARIFADO', 'KIT SERRA COPO', 1, NULL),
('ALMOXARIFADO', 'PÉ DE CABRA', 3, NULL);